In [1]:
import torch

from modules.transformer import TransformerModule
from modules.mamba import MambaModule

from dataset import FrankaDataModule

In [2]:
checkpoint = "/work/tc064/tc064/s2567498/virtual-sensing/lightning_logs/transformer/version_11/checkpoints/epoch=0-step=520.ckpt"
hparams = "/work/tc064/tc064/s2567498/virtual-sensing/lightning_logs/transformer/version_11/hparams.yaml"

In [3]:
model = TransformerModule.load_from_checkpoint(
    checkpoint_path=checkpoint, hparams_file=hparams
)

In [4]:
dm = FrankaDataModule(
    "/work/tc064/tc064/s2567498/data-w-camera",
    batch_size=1,
    num_workers=0,
    data_portion=0.1,
    episode_length=200,
    use_cpu=True,
)
dm.setup()
data_loader = dm.val_dataloader()

Using 1048/10488 data episodes. Episode length: 200


In [13]:
for batch in data_loader:
    with torch.no_grad():
        output = model.predict(batch)
        print(output)

tensor([[[ 0.0239, -0.1111, -0.1621]]])
tensor([[[ 0.0363, -0.0907,  0.0774]]])
tensor([[[ 0.0137, -0.1079, -0.1138]]])
tensor([[[ 0.0507, -0.0918,  0.0780]]])
tensor([[[ 0.0109, -0.0715,  0.1529]]])
tensor([[[ 0.0082, -0.1087, -0.0764]]])
tensor([[[-0.0044, -0.0803, -0.2436]]])
tensor([[[ 0.0788, -0.0760, -0.0191]]])
tensor([[[ 0.0625, -0.1006, -0.3371]]])
tensor([[[ 0.0435, -0.1164, -0.1533]]])
tensor([[[ 0.0547, -0.0793,  0.0949]]])
tensor([[[-0.0137, -0.1145, -0.0733]]])
tensor([[[ 0.0226, -0.0892,  0.1047]]])
tensor([[[ 0.0079, -0.1010, -0.1096]]])
tensor([[[ 0.0200, -0.0981,  0.0701]]])
tensor([[[ 0.0627, -0.1046,  0.0906]]])
tensor([[[ 0.0666, -0.1050,  0.0305]]])
tensor([[[ 0.0727, -0.0880,  0.1323]]])
tensor([[[ 0.0328, -0.0976,  0.0424]]])
tensor([[[ 0.0511, -0.1098, -0.1509]]])
tensor([[[ 0.0443, -0.1003,  0.0738]]])
tensor([[[ 0.0376, -0.1013,  0.0921]]])
tensor([[[ 0.0695, -0.0727,  0.1180]]])
tensor([[[ 0.0421, -0.0710,  0.1145]]])
tensor([[[ 0.0331, -0.0968,  0.0450]]])


KeyboardInterrupt: 